<?php
/**
 * Created by PhpStorm.
 * User: PBX_g33k
 * Date: 05/09/2018
 * Time: 22:38
 */

namespace App\Tests\Service;

use App\Entity\ExhentaiGallery;
use App\Service\ExHentaiBrowserService;
use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class ExHentaiBrowserServiceTest extends TestCase
{
    /**
     * @var MockObject|Client
     */
    private $client;

    /**
     * @var ExHentaiBrowserService
     */
    private $browser;

    /**
     * @var MockHandler
     */
    private $mockHandler;

    protected function setUp()
    {
        $this->mockHandler = new MockHandler();
        $handler = HandlerStack::create($this->mockHandler);

        $this->client = new Client(['handler' => $handler]);

        $this->browser = new ExHentaiBrowserService('','','','');
        $this->browser->setClient($this->client);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function willGetGalleriesFromListIndex()
    {
        $html = file_get_contents(__DIR__.'/../stubs/e-hentai-index-list.html');

        // Inject mock responses in handler
        $this->mockHandler->append(new Response(200, [], $html));

        $apiRequests = ceil(230/25);
        for ($i=0; $i < $apiRequests; $i++) {
            $this->mockHandler->append(new Response(200, [], '{"gmetadata": [{"gid": 618395,"token": "0439fa3666","archiver_key": "403565--d887c6dfe8aae79ed0071551aa1bafeb4a5ee361","title": "(Kouroumu 8) [Handful☆Happiness! (Fuyuki Nanahara)] TOUHOU GUNMANIA A2 (Touhou Project)","title_jpn": "(紅楼夢8) [Handful☆Happiness! (七原冬雪)] TOUHOU GUNMANIA A2 (東方Project)","category": "Non-H","thumb": "https://ehgt.org/14/63/1463dfbc16847c9ebef92c46a90e21ca881b2a12-1729712-4271-6032-jpg_l.jpg","uploader": "avexotsukaai","posted": "1376143500","filecount": "20","filesize": 51210504,"expunged": false,"rating": "4.43","torrentcount": "0","tags": ["parody:touhou project","group:handful happiness","artist:nanahra fuyuki","full color","artbook"]}]}'));
        }

        $result = $this->browser->getIndex();

        $this->assertTrue(is_array($result));
        $this->assertInstanceOf(ExhentaiGallery::class, $result[0]);
    }
}
